name: The often wrong and always confused ramblings of Dave Kinkead
highlighter: rouge
timezone: Europe/Innsbruck
permalink: /:categories/:title/
autolink: true

default: 
  class: post 

markdown: kramdown
highlighter: rouge
kramdown:
  footnote_nr: 1
  auto_ids: true
  input: GFM
