name: The often wrong and always confused ramblings of Dave Kinkead
markdown: kramdown
highlighter: true
timezone: Europe/Innsbruck
permalink: /:categories/:title
autolink: true

default: 
  class: post 