name: The often wrong and always confused ramblings of Dave Kinkead
markdown: kramdown
kramdown:
  footnote_nr: 1
  auto_ids: true
highlighter: pygments
timezone: Europe/Innsbruck
permalink: /:categories/:title
autolink: true

default: 
  class: post 